version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: sislote-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sislote
      POSTGRES_PASSWORD: sislote
      POSTGRES_DB: sislote
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
