-- Drop all tables if they exist
DROP TABLE IF EXISTS auditoria CASCADE;
DROP TABLE IF EXISTS pagamento CASCADE;
DROP TABLE IF EXISTS venda CASCADE;
DROP TABLE IF EXISTS lote CASCADE;
DROP TABLE IF EXISTS loteamento CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS conta CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS empresa CASCADE;
DROP TABLE IF EXISTS typeorm_metadata CASCADE;

-- Restart sequences
ALTER SEQUENCE IF EXISTS empresa_id_empresa_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS usuario_id_usuario_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS cliente_id_cliente_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS loteamento_id_loteamento_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS lote_id_lote_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS venda_id_venda_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS pagamento_id_pagamento_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS conta_id_conta_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS auditoria_id_auditoria_seq RESTART WITH 1;
