import { MigrationInterface, QueryRunner } from "typeorm";

export const viewSql=(usarBaixas:boolean)=>`CREATE OR REPLACE VIEW movimentos_financeiros AS
SELECT p.id_empresa,p.id_conta,p.pago_data AS data,'receita'::varchar(10) tipo,COALESCE(p.valor_pago,p.valor)::numeric(12,2) valor,'recebimento'::varchar(20) origem,p.id_pagamento id_origem,NULL::integer id_transferencia,l.id_loteamento,NULL::integer id_conta_contabil,CONCAT('Recebimento venda #',v.id_venda,' — parcela ',p.numero_parcela) descricao FROM pagamentos p JOIN vendas v ON v.id_venda=p.id_venda JOIN lotes l ON l.id_lote=v.id_lote WHERE p.situacao='pago' AND p.id_conta IS NOT NULL AND v.status<>'cancelada'
UNION ALL
${usarBaixas?`SELECT pp.id_empresa,pp.id_conta,pp.pago_data,'despesa'::varchar(10),pp.valor_pago,'pagamento'::varchar(20),pp.id_parcela_pagamento,NULL::integer,d.id_loteamento,d.id_categoria,d.descricao FROM despesa_parcela_pagamentos pp JOIN despesa_parcelas dp ON dp.id_despesa_parcela=pp.id_despesa_parcela JOIN despesas d ON d.id_despesa=dp.id_despesa UNION ALL SELECT dp.id_empresa,dp.id_conta,dp.pago_data,'despesa'::varchar(10),dp.valor_pago::numeric(12,2),'pagamento_legado'::varchar(20),dp.id_despesa_parcela,NULL::integer,d.id_loteamento,d.id_categoria,d.descricao FROM despesa_parcelas dp JOIN despesas d ON d.id_despesa=dp.id_despesa WHERE dp.situacao='pago' AND dp.id_conta IS NOT NULL AND NOT EXISTS(SELECT 1 FROM despesa_parcela_pagamentos pp WHERE pp.id_despesa_parcela=dp.id_despesa_parcela)`:`SELECT dp.id_empresa,dp.id_conta,dp.pago_data,'despesa'::varchar(10),dp.valor_pago::numeric(12,2),'pagamento'::varchar(20),dp.id_despesa_parcela,NULL::integer,d.id_loteamento,d.id_categoria,d.descricao FROM despesa_parcelas dp JOIN despesas d ON d.id_despesa=dp.id_despesa WHERE dp.situacao='pago' AND dp.id_conta IS NOT NULL`}
UNION ALL SELECT lm.id_empresa,lm.id_conta,lm.data,lm.tipo,lm.valor::numeric(12,2),'manual'::varchar(20),lm.id_lancamento,NULL::integer,lm.id_loteamento,lm.id_conta_contabil,lm.descricao FROM lancamentos_manuais lm
UNION ALL SELECT t.id_empresa,t.id_conta_origem,t.data,'despesa'::varchar(10),t.valor::numeric(12,2),'transferencia'::varchar(20),t.id_transferencia,t.id_transferencia,NULL::integer,NULL::integer,t.descricao FROM transferencias_contas t
UNION ALL SELECT t.id_empresa,t.id_conta_destino,t.data,'receita'::varchar(10),t.valor::numeric(12,2),'transferencia'::varchar(20),t.id_transferencia,t.id_transferencia,NULL::integer,NULL::integer,t.descricao FROM transferencias_contas t`;

export class CreateDespesaParcelaPagamentos1700000000039 implements MigrationInterface{
 name="CreateDespesaParcelaPagamentos1700000000039";
 async up(q:QueryRunner){await q.query(`CREATE TABLE despesa_parcela_pagamentos(id_parcela_pagamento SERIAL PRIMARY KEY,id_empresa integer NOT NULL,id_despesa_parcela integer NOT NULL REFERENCES despesa_parcelas(id_despesa_parcela) ON DELETE CASCADE,id_conta integer NOT NULL REFERENCES contas(id_conta),pago_data date NOT NULL,valor_principal numeric(12,2) NOT NULL CHECK(valor_principal>0),multa numeric(12,2) NOT NULL DEFAULT 0,juros numeric(12,2) NOT NULL DEFAULT 0,desconto numeric(12,2) NOT NULL DEFAULT 0,valor_pago numeric(12,2) NOT NULL CHECK(valor_pago>0),id_usuario integer NOT NULL REFERENCES usuarios(id_usuario),created_at timestamp NOT NULL DEFAULT now())`);await q.query(`CREATE INDEX idx_parcela_pagamentos_parcela ON despesa_parcela_pagamentos(id_despesa_parcela)`);await q.query(`INSERT INTO despesa_parcela_pagamentos(id_empresa,id_despesa_parcela,id_conta,pago_data,valor_principal,multa,juros,desconto,valor_pago,id_usuario) SELECT id_empresa,id_despesa_parcela,id_conta,pago_data,GREATEST(valor_pago-COALESCE(multa_paga,0)-COALESCE(juros_pagos,0)+COALESCE(desconto_obtido,0),0.01),COALESCE(multa_paga,0),COALESCE(juros_pagos,0),COALESCE(desconto_obtido,0),valor_pago,COALESCE(id_usuario,(SELECT MIN(u.id_usuario) FROM usuarios u WHERE u.id_empresa=despesa_parcelas.id_empresa)) FROM despesa_parcelas WHERE situacao='pago' AND id_conta IS NOT NULL AND pago_data IS NOT NULL AND valor_pago>0`);await q.query(viewSql(true));}
 async down(q:QueryRunner){await q.query(viewSql(false));await q.query(`DROP TABLE despesa_parcela_pagamentos`);}
}
