import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDownCircle, ArrowUpCircle, Eye, Flame, LockKeyhole, PiggyBank, Printer, RotateCcw, Scale, WalletCards } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DestructiveConfirmationDialog } from "@/components/ui/destructive-confirmation-dialog";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { LoadingState } from "@/components/ui/loading-state";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { formatDateBR } from "@/lib/date-br";

interface ExtratoFechamento { periodo:{from:string;to:string};saldoInicial:number;entradas:number;saidas:number;saldoFinal:number;variacaoCaixa:number;contasReceberPendentes:number;qtdReceberPendentes:number;contasPagarPendentes:number;qtdPagarPendentes:number;saldoNaoConsolidado:number }
interface MovimentoFechamento { data:string;tipo:"receita"|"despesa";descricao:string;conta:string;loteamento:string;origem:string;valor:string|number }
interface RelatorioLista { id_relatorio:number;periodo_inicio:string;periodo_fim:string;status:"fechado"|"desfeito";resumo:ExtratoFechamento;qtd_lancamentos:number;fechado_em:string;desfeito_em:string|null;fechado_por_login:string;desfeito_por_login:string|null }
interface RelatorioDetalhe extends RelatorioLista { empresa_nome:string;lancamentos:MovimentoFechamento[] }

const hoje=new Date(),dataHoje=`${hoje.getFullYear()}-${String(hoje.getMonth()+1).padStart(2,"0")}-${String(hoje.getDate()).padStart(2,"0")}`,inicioMes=`${hoje.getFullYear()}-${String(hoje.getMonth()+1).padStart(2,"0")}-01`;
const moeda=(valor:number|string)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(valor));
const dataHora=(valor:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(valor));
const escapeHtml=(valor:unknown)=>String(valor??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]!));

export function FechamentoPeriodoTab(){
  const{token}=useAuth(),{toast}=useToast(),qc=useQueryClient();const headers={Authorization:`Bearer ${token}`,"Content-Type":"application/json"};
  const[data,setData]=useState(""),[confirmar,setConfirmar]=useState(false),[desfazerId,setDesfazerId]=useState<number|null>(null),[relatorioId,setRelatorioId]=useState<number|null>(null);
  const[periodo,setPeriodo]=useState({from:inicioMes,to:dataHoje}),[periodoAplicado,setPeriodoAplicado]=useState({from:inicioMes,to:dataHoje});
  const{data:config}=useQuery<{fechado_ate:string|null;id_relatorio:number|null}>({queryKey:["fechamento-financeiro"],queryFn:async()=>{const r=await fetch("/api/fechamento-financeiro",{headers});if(!r.ok)throw new Error("Erro ao carregar fechamento");return r.json()}});
  const{data:historico=[]}=useQuery<RelatorioLista[]>({queryKey:["fechamento-financeiro","relatorios"],queryFn:async()=>{const r=await fetch("/api/fechamento-financeiro/relatorios",{headers});if(!r.ok)throw new Error("Erro ao carregar histórico");return r.json()}});
  const{data:relatorio,isLoading:carregandoRelatorio}=useQuery<RelatorioDetalhe>({queryKey:["fechamento-financeiro","relatorio",relatorioId],enabled:relatorioId!==null,queryFn:async()=>{const r=await fetch(`/api/fechamento-financeiro/relatorios/${relatorioId}`,{headers});if(!r.ok)throw new Error("Erro ao carregar relatório");return r.json()}});
  useEffect(()=>setData(config?.fechado_ate??""),[config?.fechado_ate]);
  const extrato=useQuery<ExtratoFechamento>({queryKey:["fechamento-financeiro","extrato",periodoAplicado.from,periodoAplicado.to],queryFn:async()=>{const r=await fetch(`/api/fechamento-financeiro/extrato?${new URLSearchParams(periodoAplicado)}`,{headers});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Erro ao carregar extrato do fechamento");return b}});
  const invalidar=()=>{qc.invalidateQueries({queryKey:["fechamento-financeiro"]});};
  const salvar=useMutation({mutationFn:async()=>{const r=await fetch("/api/fechamento-financeiro",{method:"PUT",headers,body:JSON.stringify({fechado_ate:data})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Erro ao efetuar fechamento");return b as{id_relatorio:number}},onSuccess:(b)=>{invalidar();setConfirmar(false);setRelatorioId(b.id_relatorio);toast({title:"Período fechado e relatório gerado"})},onError:(e:Error)=>toast({title:e.message,variant:"destructive"})});
  const desfazer=useMutation({mutationFn:async(id:number)=>{const r=await fetch(`/api/fechamento-financeiro/relatorios/${id}/desfazer`,{method:"POST",headers});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Erro ao desfazer fechamento")},onSuccess:()=>{invalidar();setDesfazerId(null);toast({title:"Fechamento desfeito","description":"O relatório foi preservado no histórico."})},onError:(e:Error)=>toast({title:e.message,variant:"destructive"})});
  const dados=extrato.data,acumulou=(dados?.variacaoCaixa??0)>=0;
  return <div className="space-y-4">
    <div className="rounded-lg border p-5 space-y-4"><div className="flex items-start gap-3"><div className="rounded-lg bg-muted p-2 text-primary"><LockKeyhole className="h-5 w-5"/></div><div><h2 className="font-semibold">Fechamento de período</h2><p className="text-sm text-muted-foreground">Bloqueia operações financeiras até a data escolhida e gera um relatório permanente dos lançamentos.</p></div></div>
      {config?.fechado_ate?<div className="rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Período atualmente fechado até <strong>{formatDateBR(config.fechado_ate)}</strong>.</div>:<div className="rounded-md border p-3 text-sm text-muted-foreground">Nenhum período está fechado.</div>}
      <div className="max-w-xs"><Label>Fechar até</Label><Input type="date" min={config?.fechado_ate||undefined} value={data} onChange={(e)=>setData(e.target.value)}/></div>
      <Button disabled={!data||data===config?.fechado_ate} onClick={()=>setConfirmar(true)}>Efetuar fechamento e gerar relatório</Button>
    </div>
    <div className="rounded-lg border p-5 space-y-5"><div><h2 className="font-semibold">Extrato do fechamento</h2><p className="text-sm text-muted-foreground">Simulação consolidada do caixa e dos compromissos pendentes.</p></div><div className="flex flex-wrap items-end gap-3"><div><Label>Início do período</Label><Input type="date" value={periodo.from} onChange={(e)=>setPeriodo(a=>({...a,from:e.target.value}))}/></div><div><Label>Fim do período</Label><Input type="date" value={periodo.to} onChange={(e)=>setPeriodo(a=>({...a,to:e.target.value}))}/></div><Button variant="outline" disabled={!periodo.from||!periodo.to||periodo.from>periodo.to} onClick={()=>setPeriodoAplicado(periodo)}>Atualizar extrato</Button></div>
      {extrato.isLoading?<LoadingState message="Calculando extrato do fechamento…"/>:extrato.isError?<div className="rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{(extrato.error as Error).message}</div>:dados?<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><ResumoCard icon={WalletCards} label="Saldo inicial" value={dados.saldoInicial} detail="Todas as contas no início do período"/><ResumoCard icon={ArrowUpCircle} label="Entradas" value={dados.entradas} detail="Receitas realizadas no período" tone="positive"/><ResumoCard icon={ArrowDownCircle} label="Saídas" value={dados.saidas} detail="Despesas realizadas no período" tone="negative"/><ResumoCard icon={PiggyBank} label="Saldo final" value={dados.saldoFinal} detail="Saldo consolidado ao fim do período"/></div><div className={`rounded-lg border p-4 ${acumulou?"border-emerald-200 bg-emerald-50":"border-red-200 bg-red-50"}`}><div className="flex items-start gap-3">{acumulou?<PiggyBank className="h-5 w-5 text-emerald-600"/>:<Flame className="h-5 w-5 text-red-600"/>}<div><p className="font-semibold">{acumulou?"O período acumulou caixa":"O período queimou caixa"}</p><p className="text-sm text-muted-foreground">Entradas menos saídas: <strong>{moeda(dados.variacaoCaixa)}</strong>.</p></div></div></div><div className="grid gap-3 sm:grid-cols-3"><ResumoCard icon={ArrowUpCircle} label="A receber não recebido" value={dados.contasReceberPendentes} detail={`${dados.qtdReceberPendentes} parcela(s) no período`} tone="positive"/><ResumoCard icon={ArrowDownCircle} label="A pagar não pago" value={dados.contasPagarPendentes} detail={`${dados.qtdPagarPendentes} parcela(s) no período`} tone="negative"/><ResumoCard icon={Scale} label="Ainda não consolidado" value={dados.saldoNaoConsolidado} detail="A receber pendente menos a pagar pendente"/></div></>:null}
    </div>
    <div className="rounded-lg border p-5 space-y-4"><div><h2 className="font-semibold">Histórico de fechamentos</h2><p className="text-sm text-muted-foreground">Relatórios preservados para consulta e reimpressão.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-muted-foreground"><th className="py-2">Período</th><th>Fechado por</th><th>Lançamentos</th><th>Status</th><th className="text-right">Ações</th></tr></thead><tbody>{historico.map((r)=><tr key={r.id_relatorio} className="border-b last:border-0"><td className="py-3">{formatDateBR(r.periodo_inicio)} a {formatDateBR(r.periodo_fim)}<div className="text-xs text-muted-foreground">{dataHora(r.fechado_em)}</div></td><td>{r.fechado_por_login}</td><td>{r.qtd_lancamentos}</td><td><Badge variant={r.status==="fechado"?"default":"secondary"}>{r.status==="fechado"?"Fechado":"Desfeito"}</Badge></td><td><div className="flex justify-end gap-1"><Button size="sm" variant="ghost" onClick={()=>setRelatorioId(r.id_relatorio)}><Eye className="mr-1 h-4 w-4"/>Visualizar</Button><Button size="sm" variant="ghost" onClick={async()=>{setRelatorioId(r.id_relatorio)}}><Printer className="mr-1 h-4 w-4"/>Reimprimir</Button>{r.status==="fechado"&&config?.id_relatorio===r.id_relatorio?<Button size="sm" variant="ghost" className="text-destructive" onClick={()=>setDesfazerId(r.id_relatorio)}><RotateCcw className="mr-1 h-4 w-4"/>Desfazer</Button>:null}</div></td></tr>)}{historico.length===0?<tr><td colSpan={5} className="py-8 text-center text-muted-foreground">Nenhum fechamento registrado.</td></tr>:null}</tbody></table></div></div>
    <DestructiveConfirmationDialog open={confirmar} onOpenChange={setConfirmar} title="Confirmar fechamento do período?" description={data?`As operações financeiras até ${formatDateBR(data)} serão bloqueadas e o relatório será gerado.`:"Selecione uma data."} consequence="O relatório ficará disponível no histórico. O fechamento poderá ser desfeito posteriormente." confirmLabel="Fechar e gerar relatório" pending={salvar.isPending} onConfirm={()=>salvar.mutate()}/>
    <DestructiveConfirmationDialog open={desfazerId!==null} onOpenChange={(v)=>!v&&setDesfazerId(null)} title="Desfazer este fechamento?" description="O período será reaberto para alterações financeiras." consequence="O relatório permanecerá no histórico com o status Desfeito e a ação será auditada." confirmLabel="Desfazer fechamento" pending={desfazer.isPending} onConfirm={()=>desfazerId&&desfazer.mutate(desfazerId)}/>
    <Dialog open={relatorioId!==null} onOpenChange={(v)=>!v&&setRelatorioId(null)}><DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Relatório de fechamento</DialogTitle><DialogDescription>Documento consolidado e lançamentos bloqueados no período.</DialogDescription></DialogHeader>{carregandoRelatorio?<LoadingState message="Carregando relatório…"/>:relatorio?<RelatorioView relatorio={relatorio} onPrint={()=>imprimirRelatorio(relatorio)}/>:null}</DialogContent></Dialog>
  </div>;
}

function ResumoCard({icon:Icon,label,value,detail,tone}:{icon:typeof WalletCards;label:string;value:number;detail:string;tone?:"positive"|"negative"}){const color=tone==="positive"?"text-emerald-600":tone==="negative"?"text-red-600":"text-foreground";return <div className="rounded-lg border p-4"><div className="flex items-center gap-2 text-sm text-muted-foreground"><Icon className="h-4 w-4"/>{label}</div><p className={`mt-2 text-xl font-bold ${color}`}>{moeda(value)}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>}
function RelatorioView({relatorio,onPrint}:{relatorio:RelatorioDetalhe;onPrint:()=>void}){const r=relatorio.resumo;return <div className="space-y-4"><div className="flex items-center justify-between"><div><p className="font-semibold">{relatorio.empresa_nome}</p><p className="text-sm text-muted-foreground">{formatDateBR(relatorio.periodo_inicio)} a {formatDateBR(relatorio.periodo_fim)} · relatório #{relatorio.id_relatorio}</p></div><Button variant="outline" onClick={onPrint}><Printer className="mr-2 h-4 w-4"/>Imprimir</Button></div><div className="grid grid-cols-2 gap-2 md:grid-cols-4"><ResumoCard icon={WalletCards} label="Saldo inicial" value={r.saldoInicial} detail="Início do período"/><ResumoCard icon={ArrowUpCircle} label="Entradas" value={r.entradas} detail="Realizadas" tone="positive"/><ResumoCard icon={ArrowDownCircle} label="Saídas" value={r.saidas} detail="Realizadas" tone="negative"/><ResumoCard icon={PiggyBank} label="Saldo final" value={r.saldoFinal} detail="Fim do período"/></div><div className="rounded-md border p-3 text-sm">Variação do caixa: <strong>{moeda(r.variacaoCaixa)}</strong> · A receber pendente: <strong>{moeda(r.contasReceberPendentes)}</strong> · A pagar pendente: <strong>{moeda(r.contasPagarPendentes)}</strong> · Ainda não consolidado: <strong>{moeda(r.saldoNaoConsolidado)}</strong></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b text-left"><th className="py-2">Data</th><th>Tipo</th><th>Descrição</th><th>Conta</th><th>Loteamento</th><th className="text-right">Valor</th></tr></thead><tbody>{relatorio.lancamentos.map((m,i)=><tr key={`${m.origem}-${i}`} className="border-b"><td className="py-2">{formatDateBR(m.data)}</td><td className={m.tipo==="receita"?"text-emerald-600":"text-red-600"}>{m.tipo==="receita"?"Entrada":"Saída"}</td><td>{m.descricao}</td><td>{m.conta}</td><td>{m.loteamento}</td><td className="text-right font-medium">{moeda(m.valor)}</td></tr>)}{relatorio.lancamentos.length===0?<tr><td colSpan={6} className="py-6 text-center text-muted-foreground">Nenhum lançamento realizado neste período.</td></tr>:null}</tbody></table></div></div>}
function imprimirRelatorio(relatorio:RelatorioDetalhe){const linhas=relatorio.lancamentos.map(m=>`<tr><td>${escapeHtml(formatDateBR(m.data))}</td><td>${m.tipo==="receita"?"Entrada":"Saída"}</td><td>${escapeHtml(m.descricao)}</td><td>${escapeHtml(m.conta)}</td><td>${escapeHtml(m.loteamento)}</td><td class="num">${moeda(m.valor)}</td></tr>`).join("");const r=relatorio.resumo,w=window.open("","_blank","width=1000,height=750");if(!w)return;w.document.write(`<!doctype html><html><head><title>Fechamento #${relatorio.id_relatorio}</title><style>body{font-family:Arial;padding:28px;color:#172033}h1{margin-bottom:4px}.meta{color:#64748b}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:24px 0}.card{border:1px solid #ddd;padding:12px;border-radius:8px}.card strong{display:block;font-size:18px;margin-top:6px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border-bottom:1px solid #ddd;padding:8px;text-align:left}.num{text-align:right}@media print{button{display:none}}</style></head><body><h1>Relatório de fechamento</h1><div class="meta">${escapeHtml(relatorio.empresa_nome)} · ${formatDateBR(relatorio.periodo_inicio)} a ${formatDateBR(relatorio.periodo_fim)} · #${relatorio.id_relatorio}</div><div class="cards"><div class="card">Saldo inicial<strong>${moeda(r.saldoInicial)}</strong></div><div class="card">Entradas<strong>${moeda(r.entradas)}</strong></div><div class="card">Saídas<strong>${moeda(r.saidas)}</strong></div><div class="card">Saldo final<strong>${moeda(r.saldoFinal)}</strong></div></div><p><strong>Variação do caixa:</strong> ${moeda(r.variacaoCaixa)} · <strong>A receber pendente:</strong> ${moeda(r.contasReceberPendentes)} · <strong>A pagar pendente:</strong> ${moeda(r.contasPagarPendentes)} · <strong>Ainda não consolidado:</strong> ${moeda(r.saldoNaoConsolidado)}</p><h2>Lançamentos bloqueados</h2><table><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Conta</th><th>Loteamento</th><th class="num">Valor</th></tr></thead><tbody>${linhas||'<tr><td colspan="6">Nenhum lançamento realizado.</td></tr>'}</tbody></table><button onclick="window.print()">Imprimir</button></body></html>`);w.document.close();w.focus()}
