"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const auth_1 = require("./modules/auth");
const clientes_1 = require("./modules/clientes");
const loteamentos_1 = require("./modules/loteamentos");
const lotes_1 = require("./modules/lotes");
const vendas_1 = require("./modules/vendas");
const pagamentos_1 = require("./modules/pagamentos");
const contas_1 = require("./modules/contas");
const usuarios_1 = require("./modules/usuarios");
const logs_1 = require("./modules/logs");
const empresas_1 = require("./modules/empresas");
const relatorios_1 = require("./modules/relatorios");
const contratos_1 = require("./modules/contratos");
const setup_1 = require("./modules/setup");
const auditoria_1 = require("./modules/auditoria");
const admin_1 = require("./modules/admin");
const hub_billing_1 = require("./modules/hub-billing");
const sugestoes_1 = require("./modules/sugestoes");
const lp_1 = require("./modules/lp");
const despesas_1 = require("./modules/despesas");
const lancamentos_1 = require("./modules/lancamentos");
const cobrancas_1 = require("./modules/cobrancas");
const regua_cobranca_1 = require("./modules/regua-cobranca");
const orcamentos_1 = require("./modules/orcamentos");
const fechamento_financeiro_1 = require("./modules/fechamento-financeiro");
const assistente_1 = require("./modules/assistente");
exports.router = (0, express_1.Router)();
exports.router.use("/lp", lp_1.lpRouter);
exports.router.use("/setup", setup_1.setupRouter);
exports.router.use("/auth", auth_1.authRouter);
exports.router.use("/clientes", clientes_1.clientesRouter);
exports.router.use("/loteamentos", loteamentos_1.loteamentosRouter);
exports.router.use("/lotes", lotes_1.lotesRouter);
exports.router.use("/vendas", vendas_1.vendasRouter);
exports.router.use("/pagamentos", pagamentos_1.pagamentosRouter);
exports.router.use("/contas", contas_1.contasRouter);
exports.router.use("/usuarios", usuarios_1.usuariosRouter);
exports.router.use("/logs", logs_1.logsRouter);
exports.router.use("/empresas", empresas_1.empresasRouter);
exports.router.use("/relatorios", relatorios_1.relatoriosRouter);
exports.router.use("/contratos", contratos_1.contratosRouter);
exports.router.use("/auditoria", auditoria_1.auditoriaRouter);
exports.router.use("/admin", admin_1.adminRouter);
exports.router.use("/hub-billing", hub_billing_1.hubBillingRouter);
exports.router.use("/sugestoes", sugestoes_1.sugestoesRouter);
exports.router.use("/despesas", despesas_1.despesasRouter);
exports.router.use("/lancamentos", lancamentos_1.lancamentosRouter);
exports.router.use("/cobrancas", cobrancas_1.cobrancasRouter);
exports.router.use("/regua-cobranca", regua_cobranca_1.reguaCobrancaRouter);
exports.router.use("/orcamentos", orcamentos_1.orcamentosRouter);
exports.router.use("/fechamento-financeiro", fechamento_financeiro_1.fechamentoFinanceiroRouter);
exports.router.use("/assistente", assistente_1.assistenteRouter);
