import{Router,Response}from"express";import{z}from"zod";import{AppDataSource}from"../../db/data-source";import{AuthRequest,requireAuth,requireFeature}from"../../middleware/auth";import{AuditoriaService}from"../../services/AuditoriaService";
export const fechamentoFinanceiroRouter=Router();fechamentoFinanceiroRouter.use(requireAuth,requireFeature("module_despesas"));
fechamentoFinanceiroRouter.get("/",async(req:AuthRequest,res:Response)=>{const[r]=await AppDataSource.query(`SELECT TO_CHAR(fechado_ate,'YYYY-MM-DD') fechado_ate,updated_at FROM fechamentos_financeiros WHERE id_empresa=$1`,[req.user!.id_empresa]);return res.json(r??{fechado_ate:null})});
const extratoQuery=z.object({from:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),to:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}).refine(({from,to})=>from<=to,{message:"A data inicial deve ser anterior ou igual à data final"});
fechamentoFinanceiroRouter.get("/extrato",async(req:AuthRequest,res:Response)=>{const p=extratoQuery.safeParse(req.query);if(!p.success)return res.status(400).json({error:"Período inválido",issues:p.error.issues});const{from,to}=p.data;const[r]=await AppDataSource.query(`
WITH saldo_base AS (SELECT COALESCE(SUM(c.saldo_inicial),0)::numeric AS valor FROM contas c WHERE c.id_empresa=$1),
movimentos_anteriores AS (SELECT COALESCE(SUM(CASE WHEN mf.tipo='receita' THEN mf.valor ELSE -mf.valor END),0)::numeric AS valor FROM movimentos_financeiros mf JOIN contas c ON c.id_conta=mf.id_conta AND c.id_empresa=$1 WHERE mf.id_empresa=$1 AND mf.data<$2::date AND mf.data>=COALESCE(c.data_saldo_inicial,'1900-01-01'::date)),
realizado AS (SELECT COALESCE(SUM(mf.valor) FILTER(WHERE mf.tipo='receita'),0)::numeric AS entradas,COALESCE(SUM(mf.valor) FILTER(WHERE mf.tipo='despesa'),0)::numeric AS saidas FROM movimentos_financeiros mf WHERE mf.id_empresa=$1 AND mf.origem IS DISTINCT FROM 'transferencia' AND mf.data BETWEEN $2::date AND $3::date),
receber_pendente AS (SELECT COALESCE(SUM(p.valor),0)::numeric AS valor,COUNT(*)::int AS quantidade FROM pagamentos p JOIN vendas v ON v.id_venda=p.id_venda WHERE p.id_empresa=$1 AND p.situacao='aberto' AND v.status<>'cancelada' AND p.vencimento BETWEEN $2::date AND $3::date),
pagar_pendente AS (SELECT COALESCE(SUM(GREATEST(dp.valor-COALESCE(baixas.liquidado,0),0)),0)::numeric AS valor,COUNT(*)::int AS quantidade FROM despesa_parcelas dp LEFT JOIN LATERAL(SELECT COALESCE(SUM(pp.valor_principal+pp.desconto),0)::numeric AS liquidado FROM despesa_parcela_pagamentos pp WHERE pp.id_despesa_parcela=dp.id_despesa_parcela AND pp.id_empresa=$1)baixas ON true WHERE dp.id_empresa=$1 AND dp.situacao<>'pago' AND dp.vencimento BETWEEN $2::date AND $3::date)
SELECT saldo_base.valor+movimentos_anteriores.valor AS saldo_inicial,realizado.entradas,realizado.saidas,saldo_base.valor+movimentos_anteriores.valor+realizado.entradas-realizado.saidas AS saldo_final,realizado.entradas-realizado.saidas AS variacao_caixa,receber_pendente.valor AS contas_receber_pendentes,receber_pendente.quantidade AS qtd_receber_pendentes,pagar_pendente.valor AS contas_pagar_pendentes,pagar_pendente.quantidade AS qtd_pagar_pendentes,receber_pendente.valor-pagar_pendente.valor AS saldo_nao_consolidado FROM saldo_base,movimentos_anteriores,realizado,receber_pendente,pagar_pendente`,[req.user!.id_empresa,from,to]);return res.json({periodo:{from,to},saldoInicial:Number(r.saldo_inicial),entradas:Number(r.entradas),saidas:Number(r.saidas),saldoFinal:Number(r.saldo_final),variacaoCaixa:Number(r.variacao_caixa),contasReceberPendentes:Number(r.contas_receber_pendentes),qtdReceberPendentes:Number(r.qtd_receber_pendentes),contasPagarPendentes:Number(r.contas_pagar_pendentes),qtdPagarPendentes:Number(r.qtd_pagar_pendentes),saldoNaoConsolidado:Number(r.saldo_nao_consolidado)});});
fechamentoFinanceiroRouter.put("/",async(req:AuthRequest,res:Response)=>{const p=z.object({fechado_ate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:"Data inválida"});const e=req.user!.id_empresa;const[a]=await AppDataSource.query(`SELECT * FROM fechamentos_financeiros WHERE id_empresa=$1`,[e]);const[s]=await AppDataSource.query(`INSERT INTO fechamentos_financeiros(id_empresa,fechado_ate,id_usuario)VALUES($1,$2,$3) ON CONFLICT(id_empresa)DO UPDATE SET fechado_ate=EXCLUDED.fechado_ate,id_usuario=EXCLUDED.id_usuario,updated_at=now() RETURNING *`,[e,p.data.fechado_ate,req.user!.id_usuario]);await AuditoriaService.registrar(req,"fechamentos_financeiros",a?"UPDATE":"CREATE",e,a,s,p.data.fechado_ate?`Período fechado até ${p.data.fechado_ate}`:"Fechamento de período removido");return res.json(s)});
