import { Router, Response } from "express";
import { z } from "zod";
import { AppDataSource } from "../../db/data-source";
import { AuthRequest, requireAuth, requireFeature } from "../../middleware/auth";
import { AuditoriaService } from "../../services/AuditoriaService";

export const reguaCobrancaRouter = Router();
reguaCobrancaRouter.use(requireAuth, requireFeature("module_pagamentos"));
const schema = z.object({ nome:z.string().trim().min(1).max(100),dias_relativos:z.number().int().min(-365).max(365),canal:z.enum(["email","whatsapp"]),assunto:z.string().trim().max(150).nullish(),mensagem:z.string().trim().min(1).max(3000),ativo:z.boolean().optional().default(false) });

reguaCobrancaRouter.get("/", async(req:AuthRequest,res:Response)=>res.json(await AppDataSource.query(`SELECT * FROM cobranca_regras WHERE id_empresa=$1 ORDER BY dias_relativos,id_regra`,[req.user!.id_empresa])));
reguaCobrancaRouter.post("/",async(req:AuthRequest,res:Response)=>{const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({error:"Dados inválidos",issues:p.error.issues});const[s]=await AppDataSource.query(`INSERT INTO cobranca_regras(id_empresa,nome,dias_relativos,canal,assunto,mensagem,ativo,id_usuario)VALUES($1,$2,$3,$4,$5,$6,$7,$8)RETURNING *`,[req.user!.id_empresa,p.data.nome,p.data.dias_relativos,p.data.canal,p.data.assunto||null,p.data.mensagem,p.data.ativo,req.user!.id_usuario]);await AuditoriaService.registrar(req,"cobranca_regras","CREATE",s.id_regra,undefined,s,"Regra de cobrança criada");return res.status(201).json(s);});
reguaCobrancaRouter.patch("/:id/status",async(req:AuthRequest,res:Response)=>{const p=z.object({ativo:z.boolean()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:"Status inválido"});const[a]=await AppDataSource.query(`SELECT * FROM cobranca_regras WHERE id_regra=$1 AND id_empresa=$2`,[Number(req.params.id),req.user!.id_empresa]);if(!a)return res.status(404).json({error:"Regra não encontrada"});const[s]=await AppDataSource.query(`UPDATE cobranca_regras SET ativo=$1,updated_at=now() WHERE id_regra=$2 AND id_empresa=$3 RETURNING *`,[p.data.ativo,a.id_regra,a.id_empresa]);await AuditoriaService.registrar(req,"cobranca_regras","UPDATE",s.id_regra,a,s,p.data.ativo?"Regra ativada":"Regra desativada");return res.json(s);});
reguaCobrancaRouter.get("/:id/preview",async(req:AuthRequest,res:Response)=>{const[r]=await AppDataSource.query(`SELECT * FROM cobranca_regras WHERE id_regra=$1 AND id_empresa=$2`,[Number(req.params.id),req.user!.id_empresa]);if(!r)return res.status(404).json({error:"Regra não encontrada"});const[c]=await AppDataSource.query(`SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE CASE WHEN $3='email' THEN NULLIF(TRIM(c.email),'') ELSE COALESCE(NULLIF(TRIM(c.fone_res),''),NULLIF(TRIM(c.fone_com),'')) END IS NOT NULL)::int AS com_contato,COALESCE(SUM(p.valor),0)::numeric AS valor FROM pagamentos p JOIN vendas v ON v.id_venda=p.id_venda JOIN clientes c ON c.id_cliente=v.id_cliente WHERE p.id_empresa=$1 AND p.situacao='aberto' AND v.status<>'cancelada' AND p.vencimento+($2::integer)=CURRENT_DATE`,[req.user!.id_empresa,r.dias_relativos,r.canal]);return res.json({regra:r,total:Number(c.total),comContato:Number(c.com_contato),semContato:Number(c.total)-Number(c.com_contato),valor:Number(c.valor),envioHabilitado:false});});
